[language-server.phel-language-server]
command = "php8.5"
args = ["./vendor/bin/phel", "lsp"]

[[language]]
name = "phel"
scope = "source.phel"
injection-regex = "(phel)"
language-id = "phel"
file-types = ["phel"]
roots = [ "phel-config.php" ]
comment-token = ";;"
language-servers = [ "phel-language-server" ]
indent = { tab-width = 2, unit = "  " }
